create table sys_function
(
    functionId       int auto_increment comment '功能ID'
        primary key,
    functionParentId int                                null comment '功能的父ID',
    functionType     varchar(255)                       null comment '功能类型[menu/permission]',
    functionIsParent int      default 0                 null comment '0子节点 1父节点',
    functionCode     varchar(255)                       null comment '功能编码[只有type= permission才有  user:view]',
    functionName     varchar(255)                       null comment '功能名称',
    functionIcon     varchar(255)                       null comment '功能图标',
    functionHref     varchar(255)                       null comment '功能链接',
    functionTarget   varchar(255)                       null comment '功能链接',
    functionIsOpen   int                                null comment '功能是否展开',
    functionOrderNum int                                null comment '功能编码',
    state            int      default 1                 null comment '功能状态【0不可用1可用】',
    remark           varchar(255)                       null,
    createTime       datetime default CURRENT_TIMESTAMP null,
    createPerson     int                                null
)
    charset = utf8;

INSERT INTO ssm.sys_function (functionId, functionParentId, functionType, functionIsParent, functionCode, functionName, functionIcon, functionHref, functionTarget, functionIsOpen, functionOrderNum, state, remark, createTime, createPerson) VALUES (2, 1, 'menu', 1, null, '基础管理', 'layui-icon-util', '', '', 0, 2, 1, null, null, null);
INSERT INTO ssm.sys_function (functionId, functionParentId, functionType, functionIsParent, functionCode, functionName, functionIcon, functionHref, functionTarget, functionIsOpen, functionOrderNum, state, remark, createTime, createPerson) VALUES (5, 1, 'menu', 1, null, '系统管理', 'layui-icon-set', '', '', 1, 5, 1, null, null, null);
INSERT INTO ssm.sys_function (functionId, functionParentId, functionType, functionIsParent, functionCode, functionName, functionIcon, functionHref, functionTarget, functionIsOpen, functionOrderNum, state, remark, createTime, createPerson) VALUES (6, 1, 'menu', 1, null, '其它管理', 'layui-icon-next', '', '', 0, 6, 1, null, null, null);
INSERT INTO ssm.sys_function (functionId, functionParentId, functionType, functionIsParent, functionCode, functionName, functionIcon, functionHref, functionTarget, functionIsOpen, functionOrderNum, state, remark, createTime, createPerson) VALUES (7, 2, 'menu', 0, null, '班级管理', 'layui-icon-user', '../classManager/classManager.action', '', 0, 7, 1, null, null, null);
INSERT INTO ssm.sys_function (functionId, functionParentId, functionType, functionIsParent, functionCode, functionName, functionIcon, functionHref, functionTarget, functionIsOpen, functionOrderNum, state, remark, createTime, createPerson) VALUES (8, 2, 'menu', 0, null, '学生管理', 'layui-icon-survey', '../studentManager/studentManager.action', '', 0, 8, 1, null, null, null);
INSERT INTO ssm.sys_function (functionId, functionParentId, functionType, functionIsParent, functionCode, functionName, functionIcon, functionHref, functionTarget, functionIsOpen, functionOrderNum, state, remark, createTime, createPerson) VALUES (9, 2, 'menu', 0, null, '教师管理', 'layui-icon-face-smile', '../teacher/teacherManager.action', '', 0, 9, 1, null, null, null);
INSERT INTO ssm.sys_function (functionId, functionParentId, functionType, functionIsParent, functionCode, functionName, functionIcon, functionHref, functionTarget, functionIsOpen, functionOrderNum, state, remark, createTime, createPerson) VALUES (15, 5, 'menu', 0, null, '菜单管理', 'layui-icon-read', '../menuManager/menuManager.action', '', 0, 15, 1, null, null, null);
INSERT INTO ssm.sys_function (functionId, functionParentId, functionType, functionIsParent, functionCode, functionName, functionIcon, functionHref, functionTarget, functionIsOpen, functionOrderNum, state, remark, createTime, createPerson) VALUES (16, 5, 'menu', 0, '', '权限管理', 'layui-icon-note', '../permission/permissionManager.action', '', 0, 16, 1, null, null, null);
INSERT INTO ssm.sys_function (functionId, functionParentId, functionType, functionIsParent, functionCode, functionName, functionIcon, functionHref, functionTarget, functionIsOpen, functionOrderNum, state, remark, createTime, createPerson) VALUES (17, 5, 'menu', 0, '', '角色管理', 'layui-icon-username', '../roleManager/roleManager.action', '', 0, 17, 1, null, null, null);
INSERT INTO ssm.sys_function (functionId, functionParentId, functionType, functionIsParent, functionCode, functionName, functionIcon, functionHref, functionTarget, functionIsOpen, functionOrderNum, state, remark, createTime, createPerson) VALUES (22, 6, 'menu', 0, null, '字典管理', 'layui-icon-list', '../dictionaryManager/dictionaryManager.action', null, 0, 22, 1, null, null, null);
INSERT INTO ssm.sys_function (functionId, functionParentId, functionType, functionIsParent, functionCode, functionName, functionIcon, functionHref, functionTarget, functionIsOpen, functionOrderNum, state, remark, createTime, createPerson) VALUES (34, 15, 'permission', 0, 'addMenu', '添加菜单', '', '', '', 0, 29, 1, null, null, null);
INSERT INTO ssm.sys_function (functionId, functionParentId, functionType, functionIsParent, functionCode, functionName, functionIcon, functionHref, functionTarget, functionIsOpen, functionOrderNum, state, remark, createTime, createPerson) VALUES (35, 15, 'permission', 0, 'updateMenuByMenuId', '修改菜单', '', null, null, 0, 30, 1, null, null, null);
INSERT INTO ssm.sys_function (functionId, functionParentId, functionType, functionIsParent, functionCode, functionName, functionIcon, functionHref, functionTarget, functionIsOpen, functionOrderNum, state, remark, createTime, createPerson) VALUES (38, 16, 'permission', 0, 'permission:create', '添加权限', '', null, null, 0, 33, 1, null, null, null);
INSERT INTO ssm.sys_function (functionId, functionParentId, functionType, functionIsParent, functionCode, functionName, functionIcon, functionHref, functionTarget, functionIsOpen, functionOrderNum, state, remark, createTime, createPerson) VALUES (39, 16, 'permission', 0, 'permission:update', '修改权限', '', null, null, 0, 34, 1, null, null, null);
INSERT INTO ssm.sys_function (functionId, functionParentId, functionType, functionIsParent, functionCode, functionName, functionIcon, functionHref, functionTarget, functionIsOpen, functionOrderNum, state, remark, createTime, createPerson) VALUES (40, 16, 'permission', 0, 'permission:delete', '删除权限', '', null, null, 0, 35, 1, null, null, null);
INSERT INTO ssm.sys_function (functionId, functionParentId, functionType, functionIsParent, functionCode, functionName, functionIcon, functionHref, functionTarget, functionIsOpen, functionOrderNum, state, remark, createTime, createPerson) VALUES (41, 16, 'permission', 0, 'permission:batchdelete', '权限批量删除', '', null, null, 0, 36, 1, null, null, null);
INSERT INTO ssm.sys_function (functionId, functionParentId, functionType, functionIsParent, functionCode, functionName, functionIcon, functionHref, functionTarget, functionIsOpen, functionOrderNum, state, remark, createTime, createPerson) VALUES (42, 17, 'permission', 0, 'role:create', '添加角色', '', null, null, 0, 37, 1, null, null, null);
INSERT INTO ssm.sys_function (functionId, functionParentId, functionType, functionIsParent, functionCode, functionName, functionIcon, functionHref, functionTarget, functionIsOpen, functionOrderNum, state, remark, createTime, createPerson) VALUES (43, 17, 'permission', 0, 'role:update', '修改角色', '', null, null, 0, 38, 1, null, null, null);
INSERT INTO ssm.sys_function (functionId, functionParentId, functionType, functionIsParent, functionCode, functionName, functionIcon, functionHref, functionTarget, functionIsOpen, functionOrderNum, state, remark, createTime, createPerson) VALUES (44, 17, 'permission', 0, 'role:delete', '删除角色', '', null, null, 0, 39, 1, null, null, null);
INSERT INTO ssm.sys_function (functionId, functionParentId, functionType, functionIsParent, functionCode, functionName, functionIcon, functionHref, functionTarget, functionIsOpen, functionOrderNum, state, remark, createTime, createPerson) VALUES (45, 17, 'permission', 0, 'role:batchdelete', '角色批量删除', '', null, null, 0, 40, 1, null, null, null);
INSERT INTO ssm.sys_function (functionId, functionParentId, functionType, functionIsParent, functionCode, functionName, functionIcon, functionHref, functionTarget, functionIsOpen, functionOrderNum, state, remark, createTime, createPerson) VALUES (46, 17, 'permission', 0, 'role:selectPermission', '分配权限', '', null, null, 0, 41, 1, null, null, null);
INSERT INTO ssm.sys_function (functionId, functionParentId, functionType, functionIsParent, functionCode, functionName, functionIcon, functionHref, functionTarget, functionIsOpen, functionOrderNum, state, remark, createTime, createPerson) VALUES (47, 18, 'permission', 0, 'user:create', '添加用户', '', null, null, 0, 42, 1, null, null, null);
INSERT INTO ssm.sys_function (functionId, functionParentId, functionType, functionIsParent, functionCode, functionName, functionIcon, functionHref, functionTarget, functionIsOpen, functionOrderNum, state, remark, createTime, createPerson) VALUES (48, 18, 'permission', 0, 'user:update', '修改用户', '', null, null, 0, 43, 1, null, null, null);
INSERT INTO ssm.sys_function (functionId, functionParentId, functionType, functionIsParent, functionCode, functionName, functionIcon, functionHref, functionTarget, functionIsOpen, functionOrderNum, state, remark, createTime, createPerson) VALUES (49, 18, 'permission', 0, 'user:delete', '删除用户', '', null, null, 0, 44, 1, null, null, null);
INSERT INTO ssm.sys_function (functionId, functionParentId, functionType, functionIsParent, functionCode, functionName, functionIcon, functionHref, functionTarget, functionIsOpen, functionOrderNum, state, remark, createTime, createPerson) VALUES (50, 18, 'permission', 0, 'user:batchdelete', '用户批量删除', '', null, null, 0, 45, 1, null, null, null);
INSERT INTO ssm.sys_function (functionId, functionParentId, functionType, functionIsParent, functionCode, functionName, functionIcon, functionHref, functionTarget, functionIsOpen, functionOrderNum, state, remark, createTime, createPerson) VALUES (51, 18, 'permission', 0, 'user:selectRole', '用户分配角色', '', null, null, 0, 46, 1, null, null, null);
INSERT INTO ssm.sys_function (functionId, functionParentId, functionType, functionIsParent, functionCode, functionName, functionIcon, functionHref, functionTarget, functionIsOpen, functionOrderNum, state, remark, createTime, createPerson) VALUES (52, 18, 'permission', 0, 'user:resetpwd', '重置密码', null, null, null, 0, 47, 1, null, null, null);
INSERT INTO ssm.sys_function (functionId, functionParentId, functionType, functionIsParent, functionCode, functionName, functionIcon, functionHref, functionTarget, functionIsOpen, functionOrderNum, state, remark, createTime, createPerson) VALUES (53, 14, 'permission', 0, 'dept:view', '部门查询', null, null, null, 0, 48, 1, null, null, null);
INSERT INTO ssm.sys_function (functionId, functionParentId, functionType, functionIsParent, functionCode, functionName, functionIcon, functionHref, functionTarget, functionIsOpen, functionOrderNum, state, remark, createTime, createPerson) VALUES (55, 16, 'permission', 0, 'permission:view', '权限查询', null, null, null, 0, 50, 1, null, null, null);
INSERT INTO ssm.sys_function (functionId, functionParentId, functionType, functionIsParent, functionCode, functionName, functionIcon, functionHref, functionTarget, functionIsOpen, functionOrderNum, state, remark, createTime, createPerson) VALUES (56, 17, 'permission', 0, 'role:view', '角色查询', null, null, null, 0, 51, 1, null, null, null);
INSERT INTO ssm.sys_function (functionId, functionParentId, functionType, functionIsParent, functionCode, functionName, functionIcon, functionHref, functionTarget, functionIsOpen, functionOrderNum, state, remark, createTime, createPerson) VALUES (57, 18, 'permission', 0, 'user:view', '用户查询', null, null, null, 0, 52, 1, null, null, null);
INSERT INTO ssm.sys_function (functionId, functionParentId, functionType, functionIsParent, functionCode, functionName, functionIcon, functionHref, functionTarget, functionIsOpen, functionOrderNum, state, remark, createTime, createPerson) VALUES (61, 1, 'menu', 1, null, '审批管理', 'layui-icon-edit', '', '', 0, 56, 1, null, null, null);
INSERT INTO ssm.sys_function (functionId, functionParentId, functionType, functionIsParent, functionCode, functionName, functionIcon, functionHref, functionTarget, functionIsOpen, functionOrderNum, state, remark, createTime, createPerson) VALUES (62, 61, 'menu', 0, null, '请假单管理', 'layui-icon-date', '../leaveBill/toLeaveBillManager.action', '', 0, 57, 1, null, null, null);
INSERT INTO ssm.sys_function (functionId, functionParentId, functionType, functionIsParent, functionCode, functionName, functionIcon, functionHref, functionTarget, functionIsOpen, functionOrderNum, state, remark, createTime, createPerson) VALUES (63, 61, 'menu', 0, null, '我的待办任务', 'layui-icon-util', '', '', 0, 58, 1, null, null, null);
INSERT INTO ssm.sys_function (functionId, functionParentId, functionType, functionIsParent, functionCode, functionName, functionIcon, functionHref, functionTarget, functionIsOpen, functionOrderNum, state, remark, createTime, createPerson) VALUES (64, 61, 'menu', 0, null, '我的审批记录', 'layui-icon-top', '', '', 0, 59, 1, null, null, null);
INSERT INTO ssm.sys_function (functionId, functionParentId, functionType, functionIsParent, functionCode, functionName, functionIcon, functionHref, functionTarget, functionIsOpen, functionOrderNum, state, remark, createTime, createPerson) VALUES (68, 8, 'permission', 0, 'loadAllStudent', '学生查询', null, '../student/loadAllStudent.action', null, null, 60, 1, null, null, null);
INSERT INTO ssm.sys_function (functionId, functionParentId, functionType, functionIsParent, functionCode, functionName, functionIcon, functionHref, functionTarget, functionIsOpen, functionOrderNum, state, remark, createTime, createPerson) VALUES (69, 8, 'permission', 0, 'addStudent', '学生添加', null, '../student/addStudent.action', null, null, 61, 1, null, null, null);
INSERT INTO ssm.sys_function (functionId, functionParentId, functionType, functionIsParent, functionCode, functionName, functionIcon, functionHref, functionTarget, functionIsOpen, functionOrderNum, state, remark, createTime, createPerson) VALUES (70, 8, 'permission', 0, 'updateStudentByStudentId', '学生修改', null, '../student/updateStudentByStudentId.action', null, null, 62, 1, null, null, null);
INSERT INTO ssm.sys_function (functionId, functionParentId, functionType, functionIsParent, functionCode, functionName, functionIcon, functionHref, functionTarget, functionIsOpen, functionOrderNum, state, remark, createTime, createPerson) VALUES (71, 8, 'permission', 0, 'student:delete', '学生删除', null, '../student/loadAllStudent.action', null, null, 63, 1, null, null, null);
INSERT INTO ssm.sys_function (functionId, functionParentId, functionType, functionIsParent, functionCode, functionName, functionIcon, functionHref, functionTarget, functionIsOpen, functionOrderNum, state, remark, createTime, createPerson) VALUES (72, 8, 'permission', 0, 'student:batchdelete', '学生批量删除', null, '../student/loadAllStudent.action', null, null, 64, 1, null, null, null);
INSERT INTO ssm.sys_function (functionId, functionParentId, functionType, functionIsParent, functionCode, functionName, functionIcon, functionHref, functionTarget, functionIsOpen, functionOrderNum, state, remark, createTime, createPerson) VALUES (73, 21, 'permission', 0, 'info:view', '日志查询', null, null, null, null, 65, 1, null, null, null);
INSERT INTO ssm.sys_function (functionId, functionParentId, functionType, functionIsParent, functionCode, functionName, functionIcon, functionHref, functionTarget, functionIsOpen, functionOrderNum, state, remark, createTime, createPerson) VALUES (74, 21, 'permission', 0, 'info:delete', '日志删除', null, null, null, null, 66, 1, null, null, null);
INSERT INTO ssm.sys_function (functionId, functionParentId, functionType, functionIsParent, functionCode, functionName, functionIcon, functionHref, functionTarget, functionIsOpen, functionOrderNum, state, remark, createTime, createPerson) VALUES (75, 21, 'permission', 0, 'info:batchdelete', '日志批量删除', null, null, null, null, 67, 1, null, null, null);
INSERT INTO ssm.sys_function (functionId, functionParentId, functionType, functionIsParent, functionCode, functionName, functionIcon, functionHref, functionTarget, functionIsOpen, functionOrderNum, state, remark, createTime, createPerson) VALUES (76, 22, 'permission', 0, 'notice:view', '公告查询', null, null, null, null, 68, 1, null, null, null);
INSERT INTO ssm.sys_function (functionId, functionParentId, functionType, functionIsParent, functionCode, functionName, functionIcon, functionHref, functionTarget, functionIsOpen, functionOrderNum, state, remark, createTime, createPerson) VALUES (77, 22, 'permission', 0, 'addDictionary', '字典添加', null, '../dictionary/addDictionary.action', null, null, 69, 1, null, null, null);
INSERT INTO ssm.sys_function (functionId, functionParentId, functionType, functionIsParent, functionCode, functionName, functionIcon, functionHref, functionTarget, functionIsOpen, functionOrderNum, state, remark, createTime, createPerson) VALUES (78, 22, 'permission', 0, 'updateByDictionaryReasonId', '字典修改', null, '../dictionary/updateByDictionaryReasonId.action', null, null, 70, 1, null, null, null);
INSERT INTO ssm.sys_function (functionId, functionParentId, functionType, functionIsParent, functionCode, functionName, functionIcon, functionHref, functionTarget, functionIsOpen, functionOrderNum, state, remark, createTime, createPerson) VALUES (79, 22, 'permission', 0, 'updateDictionaryStateByReasonId', '字典删除', null, '../dictionary/updateDictionaryStateByReasonId.action', null, null, 71, 1, null, null, null);
INSERT INTO ssm.sys_function (functionId, functionParentId, functionType, functionIsParent, functionCode, functionName, functionIcon, functionHref, functionTarget, functionIsOpen, functionOrderNum, state, remark, createTime, createPerson) VALUES (80, 22, 'permission', 0, 'updateDictionaryStateByReasonIds', '字典批量删除', null, '../dictionary/updateDictionaryStateByReasonIds.action', null, null, 72, 1, null, null, null);
INSERT INTO ssm.sys_function (functionId, functionParentId, functionType, functionIsParent, functionCode, functionName, functionIcon, functionHref, functionTarget, functionIsOpen, functionOrderNum, state, remark, createTime, createPerson) VALUES (86, 22, 'permission', 0, 'loadParentDictionary', '加载一级字典', null, '../dictionary/loadParentDictionary.action', null, null, 78, 1, null, null, null);
INSERT INTO ssm.sys_function (functionId, functionParentId, functionType, functionIsParent, functionCode, functionName, functionIcon, functionHref, functionTarget, functionIsOpen, functionOrderNum, state, remark, createTime, createPerson) VALUES (87, 99999, 'menu', 0, 'toAddStudent', '跳转添加学生页面', null, '../studentManager/addStudent.action', null, null, 79, 1, null, '2021-01-17 15:45:51', null);
INSERT INTO ssm.sys_function (functionId, functionParentId, functionType, functionIsParent, functionCode, functionName, functionIcon, functionHref, functionTarget, functionIsOpen, functionOrderNum, state, remark, createTime, createPerson) VALUES (88, 99999, 'menu', 0, 'toUpdateStudent', '跳转修改学生页面', null, '../studentManager/updateStudent.action', null, null, 80, 1, null, '2021-01-17 15:47:42', null);
INSERT INTO ssm.sys_function (functionId, functionParentId, functionType, functionIsParent, functionCode, functionName, functionIcon, functionHref, functionTarget, functionIsOpen, functionOrderNum, state, remark, createTime, createPerson) VALUES (89, 7, 'permission', 0, 'loadAllClassComboBox', '加载班级下拉框', null, '../class/loadAllClassComboBox.action', null, null, 81, 1, null, '2021-01-18 15:56:55', null);
INSERT INTO ssm.sys_function (functionId, functionParentId, functionType, functionIsParent, functionCode, functionName, functionIcon, functionHref, functionTarget, functionIsOpen, functionOrderNum, state, remark, createTime, createPerson) VALUES (90, 7, 'permission', 0, 'loadAllClass', '加载所有班级', null, '../class/loadAllClass.action', null, null, 82, 1, null, '2021-01-18 15:58:02', null);
INSERT INTO ssm.sys_function (functionId, functionParentId, functionType, functionIsParent, functionCode, functionName, functionIcon, functionHref, functionTarget, functionIsOpen, functionOrderNum, state, remark, createTime, createPerson) VALUES (91, 7, 'permission', 0, 'updateClassByClassId', '更新班级', null, '../class/updateClassByClassId.action', null, null, 83, 1, null, '2021-01-18 15:58:48', null);
INSERT INTO ssm.sys_function (functionId, functionParentId, functionType, functionIsParent, functionCode, functionName, functionIcon, functionHref, functionTarget, functionIsOpen, functionOrderNum, state, remark, createTime, createPerson) VALUES (92, 7, 'permission', 0, 'updateClassStateByClassId', '删除单个班级', null, '../class/updateClassStateByClassId.action', null, null, 84, 1, null, '2021-01-18 15:59:58', null);
INSERT INTO ssm.sys_function (functionId, functionParentId, functionType, functionIsParent, functionCode, functionName, functionIcon, functionHref, functionTarget, functionIsOpen, functionOrderNum, state, remark, createTime, createPerson) VALUES (93, 7, 'permission', 0, 'updateClassStateByClassIds', '删除多个班级', null, '../class/updateClassStateByClassIds.action', null, null, 85, 1, null, '2021-01-18 16:00:10', null);
INSERT INTO ssm.sys_function (functionId, functionParentId, functionType, functionIsParent, functionCode, functionName, functionIcon, functionHref, functionTarget, functionIsOpen, functionOrderNum, state, remark, createTime, createPerson) VALUES (94, 7, 'permission', 0, 'loadOneClassByClassId', '查看单个班级', null, '../class/loadOneClassByClassId.action', null, null, 86, 1, null, '2021-01-18 16:01:21', null);
INSERT INTO ssm.sys_function (functionId, functionParentId, functionType, functionIsParent, functionCode, functionName, functionIcon, functionHref, functionTarget, functionIsOpen, functionOrderNum, state, remark, createTime, createPerson) VALUES (95, 7, 'permission', 0, 'addClass', '添加单个班级', null, '../class/addClass.action', null, null, 87, 1, null, '2021-01-18 16:01:38', null);
INSERT INTO ssm.sys_function (functionId, functionParentId, functionType, functionIsParent, functionCode, functionName, functionIcon, functionHref, functionTarget, functionIsOpen, functionOrderNum, state, remark, createTime, createPerson) VALUES (96, 8, 'permission', 0, 'loadStudentByClassId', '根据班级加载学生', null, '../student/loadStudentByClassId.action', null, null, 88, 1, null, '2021-01-18 16:04:09', null);
INSERT INTO ssm.sys_function (functionId, functionParentId, functionType, functionIsParent, functionCode, functionName, functionIcon, functionHref, functionTarget, functionIsOpen, functionOrderNum, state, remark, createTime, createPerson) VALUES (97, 8, 'permission', 0, 'loadOneStudentByStudentId', '查询单个学生', null, '../student/loadOneStudentByStudentId.action', null, null, 89, 1, null, '2021-01-18 16:05:12', null);
INSERT INTO ssm.sys_function (functionId, functionParentId, functionType, functionIsParent, functionCode, functionName, functionIcon, functionHref, functionTarget, functionIsOpen, functionOrderNum, state, remark, createTime, createPerson) VALUES (98, 9, 'permission', 0, 'loadOneTeacherByClassId', '根据班级查询教师', null, '../teacher/loadOneTeacherByClassId.action', null, null, 90, 1, null, '2021-01-19 11:19:26', null);
INSERT INTO ssm.sys_function (functionId, functionParentId, functionType, functionIsParent, functionCode, functionName, functionIcon, functionHref, functionTarget, functionIsOpen, functionOrderNum, state, remark, createTime, createPerson) VALUES (99, 8, 'permission', 0, 'updateStudentStateByStudentId', '审批权限', null, '../student/updateStudentStateByStudentId.action', null, null, 91, 1, null, '2021-01-19 14:54:34', null);
INSERT INTO ssm.sys_function (functionId, functionParentId, functionType, functionIsParent, functionCode, functionName, functionIcon, functionHref, functionTarget, functionIsOpen, functionOrderNum, state, remark, createTime, createPerson) VALUES (100, 99999, 'menu', 0, null, '添加菜单', 'layui-icon-read', '../menuManager/addMenu.action', '', 0, 15, 1, null, null, null);
INSERT INTO ssm.sys_function (functionId, functionParentId, functionType, functionIsParent, functionCode, functionName, functionIcon, functionHref, functionTarget, functionIsOpen, functionOrderNum, state, remark, createTime, createPerson) VALUES (101, 99999, 'menu', 0, '', '跳转资源分配', 'layui-icon-username', '../roleManager/sourceAllot.action', '', 0, 17, 1, null, null, null);
INSERT INTO ssm.sys_function (functionId, functionParentId, functionType, functionIsParent, functionCode, functionName, functionIcon, functionHref, functionTarget, functionIsOpen, functionOrderNum, state, remark, createTime, createPerson) VALUES (102, 15, 'permission', 0, 'loadAllMenu', '加载所有菜单', null, null, null, 0, 100, 1, null, '2021-01-19 22:08:21', null);
INSERT INTO ssm.sys_function (functionId, functionParentId, functionType, functionIsParent, functionCode, functionName, functionIcon, functionHref, functionTarget, functionIsOpen, functionOrderNum, state, remark, createTime, createPerson) VALUES (103, 15, 'permission', 0, 'queryOneMenu', '查询一个菜单', null, null, null, 0, 101, 1, null, '2021-01-19 22:10:20', null);
INSERT INTO ssm.sys_function (functionId, functionParentId, functionType, functionIsParent, functionCode, functionName, functionIcon, functionHref, functionTarget, functionIsOpen, functionOrderNum, state, remark, createTime, createPerson) VALUES (104, 15, 'permission', 0, 'loadTreeFunction', '加载菜单树结构', null, null, null, 0, 102, 1, null, '2021-01-19 22:13:00', null);
INSERT INTO ssm.sys_function (functionId, functionParentId, functionType, functionIsParent, functionCode, functionName, functionIcon, functionHref, functionTarget, functionIsOpen, functionOrderNum, state, remark, createTime, createPerson) VALUES (105, 99999, 'menu', 0, null, '跳转菜单修改', null, '../menuManager/updateMenu.action', null, null, null, 1, null, '2021-01-19 22:14:35', null);
INSERT INTO ssm.sys_function (functionId, functionParentId, functionType, functionIsParent, functionCode, functionName, functionIcon, functionHref, functionTarget, functionIsOpen, functionOrderNum, state, remark, createTime, createPerson) VALUES (106, 9999, 'menu', 0, null, '跳转菜单修改', '', '../menuManager/updateMenu.action', null, 0, 102, 1, '跳转菜单修改', '2021-01-19 22:15:29', 20);
INSERT INTO ssm.sys_function (functionId, functionParentId, functionType, functionIsParent, functionCode, functionName, functionIcon, functionHref, functionTarget, functionIsOpen, functionOrderNum, state, remark, createTime, createPerson) VALUES (107, 15, 'permission', 0, 'batchDeleteMenu', '批量删除菜单', null, null, null, null, 103, 1, null, '2021-01-19 22:24:03', null);
INSERT INTO ssm.sys_function (functionId, functionParentId, functionType, functionIsParent, functionCode, functionName, functionIcon, functionHref, functionTarget, functionIsOpen, functionOrderNum, state, remark, createTime, createPerson) VALUES (108, 15, 'permission', 0, 'deleteMenu', '删除一个菜单', null, null, null, null, 103, 1, null, '2021-01-19 22:24:03', null);
INSERT INTO ssm.sys_function (functionId, functionParentId, functionType, functionIsParent, functionCode, functionName, functionIcon, functionHref, functionTarget, functionIsOpen, functionOrderNum, state, remark, createTime, createPerson) VALUES (109, 99999, 'menu', 0, null, '跳转角色修改', '', '../roleManager/updateRole.action', null, 0, 105, 1, '跳转角色修改', '2021-01-19 22:26:59', 20);